{
    "type": "bundle",
    "id": "bundle--19a353d1-4658-467b-b563-825c831a3fed",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--ab0a4dec-fc7b-4280-9231-9ae04d664810",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-07-11T00:31:39.887282Z",
            "modified": "2024-07-11T00:31:39.887282Z",
            "name": "CVE-2024-39614",
            "description": "An issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2.14. get_supported_language_variant() was subject to a potential denial-of-service attack when used with very long strings containing specific characters.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-39614"
                }
            ]
        }
    ]
}