{
    "type": "bundle",
    "id": "bundle--8db845e8-96ea-40a3-8151-b86f93b3ed9e",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--bb35dd6b-6587-48d4-8e6b-adaffc0dda56",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-04-25T00:30:14.623173Z",
            "modified": "2024-04-25T00:30:14.623173Z",
            "name": "CVE-2024-32879",
            "description": "Python Social Auth is a social authentication/registration mechanism. Prior to version 5.4.1, due to default case-insensitive collation in MySQL or MariaDB databases, third-party authentication user IDs are not case-sensitive and could cause different IDs to match. This issue has been addressed by a fix released in version 5.4.1. An immediate workaround would be to change collation of the affected field.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-32879"
                }
            ]
        }
    ]
}