{
    "type": "bundle",
    "id": "bundle--58bcdd05-247f-4fb8-a16a-5db30ba0efae",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--00ff02e2-1371-45ef-bd6b-d242ec9987e8",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-04-11T00:28:30.800801Z",
            "modified": "2024-04-11T00:28:30.800801Z",
            "name": "CVE-2024-30692",
            "description": "A issue was discovered in ROS2 Galactic Geochelone versions ROS_VERSION 2 and ROS_PYTHON_VERSION 3, allows remote attackers to cause a denial of service (DoS) in the ROS2 nodes.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-30692"
                }
            ]
        }
    ]
}