{
    "type": "bundle",
    "id": "bundle--b91c7ab3-0d7b-477c-a846-6cf182774cd2",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--ee697f92-8307-4f8d-9abf-ad8c7fcf62f2",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-06-25T00:20:55.776118Z",
            "modified": "2021-06-25T00:20:55.776118Z",
            "name": "CVE-2021-32492",
            "description": "A flaw was found in djvulibre-3.5.28 and earlier. An out of bounds read in function DJVU::DataPool::has_data() via crafted djvu file may lead to application crash and other consequences.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2021-32492"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}