{
    "type": "bundle",
    "id": "bundle--4f6b1fd9-5554-463f-a4ea-e72322ba64f0",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--81c8992d-5d42-4684-8f5b-ae0b0c1044fd",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-07-11T00:31:39.483858Z",
            "modified": "2024-07-11T00:31:39.483858Z",
            "name": "CVE-2024-38875",
            "description": "An issue was discovered in Django 4.2 before 4.2.14 and 5.0 before 5.0.7. urlize and urlizetrunc were subject to a potential denial of service attack via certain inputs with a very large number of brackets.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-38875"
                }
            ]
        }
    ]
}