{
    "type": "bundle",
    "id": "bundle--90f2f091-1a5f-40c8-a1f0-b55b247eaf6c",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--c2773536-4270-4261-b89c-adb74fa90c88",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-04-18T00:27:51.048155Z",
            "modified": "2024-04-18T00:27:51.048155Z",
            "name": "CVE-2024-26920",
            "description": "In the Linux kernel, the following vulnerability has been resolved:\n\ntracing/trigger: Fix to return error if failed to alloc snapshot\n\nFix register_snapshot_trigger() to return error code if it failed to\nallocate a snapshot instead of 0 (success). Unless that, it will register\nsnapshot trigger without an error.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-26920"
                }
            ]
        }
    ]
}